### ISSUE TITLE
Doesn't work in my react native app.

### ISSUE THREAD

**Issue by GokulRG** [osagie/react-native-hideable-view#3]
As soon as I import HideableView, it simply says undefined is not an object (evaluating '_react.PropTypes.bool')

**Comment by agriardyan** [comment]
I think the error came from wrong import package in HidableView.js. As the docs here (https://facebook.github.io/react/docs/typechecking-with-proptypes.html) said :

> React.PropTypes has moved into a different package since React v15.5. Please use the prop-types library instead.

Since this project using react version "react": ">=15.2.0", temporary fix (while waiting my PR #4 to be merged) is go to HidableView.js, move the PropTypes from :
import React, { Component, **PropTypes** } from 'react'
to
import { PropTypes } from 'prop-types'

**Comment by osagie** [comment]
#4
